[package]
name = "blitstr"
version = "0.5.0"
authors = ["samblenny"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
rkyv = { version = "0.3.1", default_features = false }
log = "0.4"

[lib]
doctest = false

[features]
# romfont = []
default = []
